// This file is auto generated from elf.h header file.
#include <string>

/**
 * Returns the text description of a machine architecture.
 */
std::string get_machine_description(unsigned int machine)
{
    std::string description;

    switch(machine)
    {
        case 0: description = "No machine"; break; // EM_NONE
        case 1: description = "AT&T WE 32100"; break; // EM_M32
        case 2: description = "SUN SPARC"; break; // EM_SPARC
        case 3: description = "Intel 80386"; break; // EM_386
        case 4: description = "Motorola m68k family"; break; // EM_68K
        case 5: description = "Motorola m88k family"; break; // EM_88K
        case 6: description = "Intel MCU"; break; // EM_IAMCU
        case 7: description = "Intel 80860"; break; // EM_860
        case 8: description = "MIPS R3000 big-endian"; break; // EM_MIPS
        case 9: description = "IBM System/370"; break; // EM_S370
        case 10: description = "MIPS R3000 little-endian"; break; // EM_MIPS_RS3_LE
        case 15: description = "HPPA"; break; // EM_PARISC
        case 17: description = "Fujitsu VPP500"; break; // EM_VPP500
        case 18: description = "Sun's \"v8plus\""; break; // EM_SPARC32PLUS
        case 19: description = "Intel 80960"; break; // EM_960
        case 20: description = "PowerPC"; break; // EM_PPC
        case 21: description = "PowerPC 64-bit"; break; // EM_PPC64
        case 22: description = "IBM S390"; break; // EM_S390
        case 23: description = "IBM SPU/SPC"; break; // EM_SPU
        case 36: description = "NEC V800 series"; break; // EM_V800
        case 37: description = "Fujitsu FR20"; break; // EM_FR20
        case 38: description = "TRW RH-32"; break; // EM_RH32
        case 39: description = "Motorola RCE"; break; // EM_RCE
        case 40: description = "ARM"; break; // EM_ARM
        case 41: description = "Digital Alpha"; break; // EM_FAKE_ALPHA
        case 42: description = "Hitachi SH"; break; // EM_SH
        case 43: description = "SPARC v9 64-bit"; break; // EM_SPARCV9
        case 44: description = "Siemens Tricore"; break; // EM_TRICORE
        case 45: description = "Argonaut RISC Core"; break; // EM_ARC
        case 46: description = "Hitachi H8/300"; break; // EM_H8_300
        case 47: description = "Hitachi H8/300H"; break; // EM_H8_300H
        case 48: description = "Hitachi H8S"; break; // EM_H8S
        case 49: description = "Hitachi H8/500"; break; // EM_H8_500
        case 50: description = "Intel Merced"; break; // EM_IA_64
        case 51: description = "Stanford MIPS-X"; break; // EM_MIPS_X
        case 52: description = "Motorola Coldfire"; break; // EM_COLDFIRE
        case 53: description = "Motorola M68HC12"; break; // EM_68HC12
        case 54: description = "Fujitsu MMA Multimedia Accelerator"; break; // EM_MMA
        case 55: description = "Siemens PCP"; break; // EM_PCP
        case 56: description = "Sony nCPU embeeded RISC"; break; // EM_NCPU
        case 57: description = "Denso NDR1 microprocessor"; break; // EM_NDR1
        case 58: description = "Motorola Start*Core processor"; break; // EM_STARCORE
        case 59: description = "Toyota ME16 processor"; break; // EM_ME16
        case 60: description = "STMicroelectronic ST100 processor"; break; // EM_ST100
        case 61: description = "Advanced Logic Corp. Tinyj emb.fam"; break; // EM_TINYJ
        case 62: description = "AMD x86-64 architecture"; break; // EM_X86_64
        case 63: description = "Sony DSP Processor"; break; // EM_PDSP
        case 64: description = "Digital PDP-10"; break; // EM_PDP10
        case 65: description = "Digital PDP-11"; break; // EM_PDP11
        case 66: description = "Siemens FX66 microcontroller"; break; // EM_FX66
        case 67: description = "STMicroelectronics ST9+ 8/16 mc"; break; // EM_ST9PLUS
        case 68: description = "STmicroelectronics ST7 8 bit mc"; break; // EM_ST7
        case 69: description = "Motorola MC68HC16 microcontroller"; break; // EM_68HC16
        case 70: description = "Motorola MC68HC11 microcontroller"; break; // EM_68HC11
        case 71: description = "Motorola MC68HC08 microcontroller"; break; // EM_68HC08
        case 72: description = "Motorola MC68HC05 microcontroller"; break; // EM_68HC05
        case 73: description = "Silicon Graphics SVx"; break; // EM_SVX
        case 74: description = "STMicroelectronics ST19 8 bit mc"; break; // EM_ST19
        case 75: description = "Digital VAX"; break; // EM_VAX
        case 76: description = "Axis Communications 32-bit emb.proc"; break; // EM_CRIS
        case 77: description = "Infineon Technologies 32-bit emb.proc"; break; // EM_JAVELIN
        case 78: description = "Element 14 64-bit DSP Processor"; break; // EM_FIREPATH
        case 79: description = "LSI Logic 16-bit DSP Processor"; break; // EM_ZSP
        case 80: description = "Donald Knuth's educational 64-bit proc"; break; // EM_MMIX
        case 81: description = "Harvard University machine-independent object files"; break; // EM_HUANY
        case 82: description = "SiTera Prism"; break; // EM_PRISM
        case 83: description = "Atmel AVR 8-bit microcontroller"; break; // EM_AVR
        case 84: description = "Fujitsu FR30"; break; // EM_FR30
        case 85: description = "Mitsubishi D10V"; break; // EM_D10V
        case 86: description = "Mitsubishi D30V"; break; // EM_D30V
        case 87: description = "NEC v850"; break; // EM_V850
        case 88: description = "Mitsubishi M32R"; break; // EM_M32R
        case 89: description = "Matsushita MN10300"; break; // EM_MN10300
        case 90: description = "Matsushita MN10200"; break; // EM_MN10200
        case 91: description = "picoJava"; break; // EM_PJ
        case 92: description = "OpenRISC 32-bit embedded processor"; break; // EM_OPENRISC
        case 93: description = "ARC International ARCompact"; break; // EM_ARC_COMPACT
        case 94: description = "Tensilica Xtensa Architecture"; break; // EM_XTENSA
        case 95: description = "Alphamosaic VideoCore"; break; // EM_VIDEOCORE
        case 96: description = "Thompson Multimedia General Purpose Proc"; break; // EM_TMM_GPP
        case 97: description = "National Semi. 32000"; break; // EM_NS32K
        case 98: description = "Tenor Network TPC"; break; // EM_TPC
        case 99: description = "Trebia SNP 1000"; break; // EM_SNP1K
        case 100: description = "STMicroelectronics ST200"; break; // EM_ST200
        case 101: description = "Ubicom IP2xxx"; break; // EM_IP2K
        case 102: description = "MAX processor"; break; // EM_MAX
        case 103: description = "National Semi. CompactRISC"; break; // EM_CR
        case 104: description = "Fujitsu F2MC16"; break; // EM_F2MC16
        case 105: description = "Texas Instruments msp430"; break; // EM_MSP430
        case 106: description = "Analog Devices Blackfin DSP"; break; // EM_BLACKFIN
        case 107: description = "Seiko Epson S1C33 family"; break; // EM_SE_C33
        case 108: description = "Sharp embedded microprocessor"; break; // EM_SEP
        case 109: description = "Arca RISC"; break; // EM_ARCA
        case 110: description = "PKU-Unity & MPRC Peking Uni. mc series"; break; // EM_UNICORE
        case 111: description = "eXcess configurable cpu"; break; // EM_EXCESS
        case 112: description = "Icera Semi. Deep Execution Processor"; break; // EM_DXP
        case 113: description = "Altera Nios II"; break; // EM_ALTERA_NIOS2
        case 114: description = "National Semi. CompactRISC CRX"; break; // EM_CRX
        case 115: description = "Motorola XGATE"; break; // EM_XGATE
        case 116: description = "Infineon C16x/XC16x"; break; // EM_C166
        case 117: description = "Renesas M16C"; break; // EM_M16C
        case 118: description = "Microchip Technology dsPIC30F"; break; // EM_DSPIC30F
        case 119: description = "Freescale Communication Engine RISC"; break; // EM_CE
        case 120: description = "Renesas M32C"; break; // EM_M32C
        case 131: description = "Altium TSK3000"; break; // EM_TSK3000
        case 132: description = "Freescale RS08"; break; // EM_RS08
        case 133: description = "Analog Devices SHARC family"; break; // EM_SHARC
        case 134: description = "Cyan Technology eCOG2"; break; // EM_ECOG2
        case 135: description = "Sunplus S+core7 RISC"; break; // EM_SCORE7
        case 136: description = "New Japan Radio (NJR) 24-bit DSP"; break; // EM_DSP24
        case 137: description = "Broadcom VideoCore III"; break; // EM_VIDEOCORE3
        case 138: description = "RISC for Lattice FPGA"; break; // EM_LATTICEMICO32
        case 139: description = "Seiko Epson C17"; break; // EM_SE_C17
        case 140: description = "Texas Instruments TMS320C6000 DSP"; break; // EM_TI_C6000
        case 141: description = "Texas Instruments TMS320C2000 DSP"; break; // EM_TI_C2000
        case 142: description = "Texas Instruments TMS320C55x DSP"; break; // EM_TI_C5500
        case 143: description = "Texas Instruments App. Specific RISC"; break; // EM_TI_ARP32
        case 144: description = "Texas Instruments Prog. Realtime Unit"; break; // EM_TI_PRU
        case 160: description = "STMicroelectronics 64bit VLIW DSP"; break; // EM_MMDSP_PLUS
        case 161: description = "Cypress M8C"; break; // EM_CYPRESS_M8C
        case 162: description = "Renesas R32C"; break; // EM_R32C
        case 163: description = "NXP Semi. TriMedia"; break; // EM_TRIMEDIA
        case 164: description = "QUALCOMM DSP6"; break; // EM_QDSP6
        case 165: description = "Intel 8051 and variants"; break; // EM_8051
        case 166: description = "STMicroelectronics STxP7x"; break; // EM_STXP7X
        case 167: description = "Andes Tech. compact code emb. RISC"; break; // EM_NDS32
        case 168: description = "Cyan Technology eCOG1X"; break; // EM_ECOG1X
        case 169: description = "Dallas Semi. MAXQ30 mc"; break; // EM_MAXQ30
        case 170: description = "New Japan Radio (NJR) 16-bit DSP"; break; // EM_XIMO16
        case 171: description = "M2000 Reconfigurable RISC"; break; // EM_MANIK
        case 172: description = "Cray NV2 vector architecture"; break; // EM_CRAYNV2
        case 173: description = "Renesas RX"; break; // EM_RX
        case 174: description = "Imagination Tech. META"; break; // EM_METAG
        case 175: description = "MCST Elbrus"; break; // EM_MCST_ELBRUS
        case 176: description = "Cyan Technology eCOG16"; break; // EM_ECOG16
        case 177: description = "National Semi. CompactRISC CR16"; break; // EM_CR16
        case 178: description = "Freescale Extended Time Processing Unit"; break; // EM_ETPU
        case 179: description = "Infineon Tech. SLE9X"; break; // EM_SLE9X
        case 180: description = "Intel L10M"; break; // EM_L10M
        case 181: description = "Intel K10M"; break; // EM_K10M
        case 183: description = "ARM AARCH64"; break; // EM_AARCH64
        case 185: description = "Amtel 32-bit microprocessor"; break; // EM_AVR32
        case 186: description = "STMicroelectronics STM8"; break; // EM_STM8
        case 187: description = "Tileta TILE64"; break; // EM_TILE64
        case 188: description = "Tilera TILEPro"; break; // EM_TILEPRO
        case 189: description = "Xilinx MicroBlaze"; break; // EM_MICROBLAZE
        case 190: description = "NVIDIA CUDA"; break; // EM_CUDA
        case 191: description = "Tilera TILE-Gx"; break; // EM_TILEGX
        case 192: description = "CloudShield"; break; // EM_CLOUDSHIELD
        case 193: description = "KIPO-KAIST Core-A 1st gen."; break; // EM_COREA_1ST
        case 194: description = "KIPO-KAIST Core-A 2nd gen."; break; // EM_COREA_2ND
        case 195: description = "Synopsys ARCompact V2"; break; // EM_ARC_COMPACT2
        case 196: description = "Open8 RISC"; break; // EM_OPEN8
        case 197: description = "Renesas RL78"; break; // EM_RL78
        case 198: description = "Broadcom VideoCore V"; break; // EM_VIDEOCORE5
        case 199: description = "Renesas 78KOR"; break; // EM_78KOR
        case 200: description = "Freescale 56800EX DSC"; break; // EM_56800EX
        case 201: description = "Beyond BA1"; break; // EM_BA1
        case 202: description = "Beyond BA2"; break; // EM_BA2
        case 203: description = "XMOS xCORE"; break; // EM_XCORE
        case 204: description = "Microchip 8-bit PIC(r)"; break; // EM_MCHP_PIC
        case 210: description = "KM211 KM32"; break; // EM_KM32
        case 211: description = "KM211 KMX32"; break; // EM_KMX32
        case 212: description = "KM211 KMX16"; break; // EM_EMX16
        case 213: description = "KM211 KMX8"; break; // EM_EMX8
        case 214: description = "KM211 KVARC"; break; // EM_KVARC
        case 215: description = "Paneve CDP"; break; // EM_CDP
        case 216: description = "Cognitive Smart Memory Processor"; break; // EM_COGE
        case 217: description = "Bluechip CoolEngine"; break; // EM_COOL
        case 218: description = "Nanoradio Optimized RISC"; break; // EM_NORC
        case 219: description = "CSR Kalimba"; break; // EM_CSR_KALIMBA
        case 220: description = "Zilog Z80"; break; // EM_Z80
        case 221: description = "Controls and Data Services VISIUMcore"; break; // EM_VISIUM
        case 222: description = "FTDI Chip FT32"; break; // EM_FT32
        case 223: description = "Moxie processor"; break; // EM_MOXIE
        case 224: description = "AMD GPU"; break; // EM_AMDGPU
        case 243: description = "RISC-V"; break; // EM_RISCV
        case 247: description = "Linux BPF -- in-kernel virtual machine"; break; // EM_BPF
        default: description = "Unknown 'e_machine' type"; break;
    };

    return description;
}